# Generated by Django 5.2.17 on 2026-09-24 18:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('retired', 'Retired')], db_index=True, default='hidden', max_length=16)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='active', max_length=16)),
                ('max_accounts', models.PositiveIntegerField(blank=True, help_text='Blank means no fixed limit.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('retired', 'Retired')], db_index=True, default='hidden', max_length=16)),
                ('type', models.CharField(choices=[('shared_hosting', 'Shared Hosting'), ('wordpress_hosting', 'WordPress Hosting'), ('reseller_hosting', 'Reseller Hosting'), ('vps', 'VPS'), ('dedicated_server', 'Dedicated Server')], db_index=True, max_length=32)),
                ('resource_limits', models.JSONField(blank=True, default=dict, help_text='e.g. {"disk_mb": 5000, "bandwidth_mb": null} (null = unlimited).')),
                ('whm_package_name', models.CharField(blank=True, help_text='WHM package this product creates.', max_length=100)),
                ('auto_setup', models.BooleanField(default=True, help_text='Provision automatically on payment once Phase 05 is live. Off = staff provision manually.')),
                ('default_auto_renew', models.BooleanField(default=True, help_text='Default for new orders of this product.')),
                ('servers', models.ManyToManyField(blank=True, related_name='products', to='products.server')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annually'), ('annual', 'Annually'), ('biennial', 'Biennially'), ('custom', 'Custom'), ('one_time', 'One-time')], max_length=16)),
                ('custom_months', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.addon')),
            ],
            options={
                'ordering': ['billing_cycle', 'custom_months'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('addon', 'billing_cycle', 'custom_months'), name='unique_addon_price')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annually'), ('annual', 'Annually'), ('biennial', 'Biennially'), ('custom', 'Custom'), ('one_time', 'One-time')], max_length=16)),
                ('custom_months', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'ordering': ['billing_cycle', 'custom_months'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('product', 'billing_cycle', 'custom_months'), name='unique_product_price')],
            },
        ),
    ]
