# Generated by Django 5.2.17 on 2026-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='api_port',
            field=models.PositiveIntegerField(default=2087, help_text='WHM API port. 2087 is the standard port.'),
        ),
        migrations.AddField(
            model_name='server',
            name='api_token_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='server',
            name='api_username',
            field=models.CharField(blank=True, help_text='WHM API username, e.g. "root".', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual (no real provisioning - development/testing only)'), ('whm_api', 'WHM API')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Use HTTPS for the WHM API connection.'),
        ),
        migrations.AddField(
            model_name='server',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Disable only for a self-signed certificate you trust.'),
        ),
    ]
