# Generated by Django 5.2.17 on 2026-09-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_server_api_port_server_api_token_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_addons',
            field=models.ManyToManyField(blank=True, help_text='Add-ons to highlight with this plan.', related_name='recommended_for', to='products.addon'),
        ),
        migrations.AddField(
            model_name='product',
            name='upsell_product',
            field=models.ForeignKey(blank=True, help_text='A bigger plan to suggest in the cart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsold_from', to='products.product'),
        ),
    ]
