# Generated by Django 5.2.17 on 2026-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_guest_carts_and_upsells'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='kind',
            field=models.CharField(choices=[('general', 'Add-on for a hosting plan'), ('ssl', 'SSL certificate (for a hosting plan)'), ('whois_privacy', 'WHOIS privacy (for a domain)')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('shared_hosting', 'Shared Hosting'), ('wordpress_hosting', 'WordPress Hosting'), ('business_hosting', 'Business Hosting'), ('ecommerce_hosting', 'E-commerce Hosting'), ('reseller_hosting', 'Reseller Hosting'), ('vps', 'VPS'), ('dedicated_server', 'Dedicated Server')], db_index=True, max_length=32),
        ),
    ]
