# Generated by Django 5.2.17 on 2026-09-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('hosting', '0002_phase08_terms'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_reason',
            field=models.CharField(blank=True, help_text='Why the order is in a fraud/failed/suspended/terminated state.', max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfilment_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hosting_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='hosting.hostingaccount'),
        ),
    ]
