# Generated by Django 5.2.17 on 2026-09-24 17:14

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_users', 'Can view staff and customer user accounts'), ('view_clients', 'Can view clients'), ('view_products', 'Can view products and pricing'), ('view_orders', 'Can view orders'), ('view_billing', 'Can view invoices and transactions'), ('view_domains', 'Can view domains'), ('view_hosting', 'Can view hosting services'), ('view_support', 'Can view support tickets'), ('view_reports', 'Can view reports'), ('view_providers', 'Can view provider connections'), ('view_settings', 'Can view system settings'), ('manage_users', 'Can manage staff and customer user accounts'), ('manage_clients', 'Can manage clients'), ('manage_products', 'Can manage products and pricing'), ('manage_orders', 'Can manage orders'), ('manage_billing', 'Can manage invoices and transactions'), ('manage_domains', 'Can manage domains'), ('manage_hosting', 'Can manage hosting services'), ('manage_support', 'Can manage support tickets'), ('manage_reports', 'Can manage reports'), ('manage_providers', 'Can manage provider connections'), ('manage_settings', 'Can manage system settings'), ('assign_roles', 'Can assign staff roles'), ('view_audit_log', 'Can view the audit log')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('support_agent', 'Support Agent'), ('manager', 'Manager'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, default='customer', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_staff', models.BooleanField(default=False, editable=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
