# Generated by Django 5.2.17 on 2026-09-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_users', 'Can view staff and customer user accounts'), ('view_clients', 'Can view clients'), ('view_products', 'Can view products and pricing'), ('view_orders', 'Can view orders'), ('view_billing', 'Can view invoices and transactions'), ('view_domains', 'Can view domains'), ('view_hosting', 'Can view hosting services'), ('view_support', 'Can view support tickets'), ('view_affiliates', 'Can view affiliates, commissions and payouts'), ('view_reports', 'Can view reports'), ('view_providers', 'Can view provider connections'), ('view_settings', 'Can view system settings'), ('manage_users', 'Can manage staff and customer user accounts'), ('manage_clients', 'Can manage clients'), ('manage_products', 'Can manage products and pricing'), ('manage_orders', 'Can manage orders'), ('manage_billing', 'Can manage invoices and transactions'), ('manage_domains', 'Can manage domains'), ('manage_hosting', 'Can manage hosting services'), ('manage_support', 'Can manage support tickets'), ('manage_affiliates', 'Can manage affiliates, commissions and payouts'), ('manage_reports', 'Can manage reports'), ('manage_providers', 'Can manage provider connections'), ('manage_settings', 'Can manage system settings'), ('assign_roles', 'Can assign staff roles'), ('view_audit_log', 'Can view the audit log')]},
        ),
    ]
