# Generated by Django 5.2.17 on 2026-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_portalaccess_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('support_agent', 'Support Agent'), ('technical', 'Technical Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, default='customer', max_length=32),
        ),
    ]
