# Generated by Django 5.2.17 on 2026-09-25 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='renewal_invoice_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Renewal invoices are created this many days before a service expires.', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
    ]
