# Generated by Django 5.2.17 on 2026-09-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_phase08_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='send_payment_reminders',
            field=models.BooleanField(default=True, help_text='Email customers before an invoice is due and when it becomes overdue.'),
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='billing.invoice')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'kind'), name='unique_reminder_per_invoice_kind')],
            },
        ),
    ]
