# Generated by Django 5.2.17 on 2026-09-24 19:10

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TldPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tld', models.CharField(help_text='Including the dot, e.g. ".com".', max_length=20, unique=True)),
                ('register_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('renew_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('redemption_price', models.DecimalField(decimal_places=2, default=0, help_text='Fee to recover a domain shortly after it expires, where the registry supports it.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_years', models.PositiveSmallIntegerField(default=1)),
                ('max_years', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tld'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=253, validators=[django.core.validators.RegexValidator(re.compile('^(?=.{1,253}$)(?:[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z]{2,63}$'), 'Enter a valid domain name, e.g. example.com.')])),
                ('tld', models.CharField(db_index=True, editable=False, max_length=20)),
                ('status', models.CharField(choices=[('pending_registration', 'Pending Registration'), ('pending_transfer_in', 'Pending Transfer'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending_registration', max_length=24)),
                ('years', models.PositiveSmallIntegerField(default=1)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=True, help_text='Registrar transfer lock.')),
                ('nameservers', models.JSONField(blank=True, default=list)),
                ('auth_code_encrypted', models.TextField(blank=True, editable=False)),
                ('provider_ref', models.CharField(blank=True, help_text="Registrar's reference for this domain.", max_length=100)),
                ('last_error', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('SRV', 'SRV')], max_length=8)),
                ('name', models.CharField(blank=True, help_text='Subdomain part, blank for the root.', max_length=253)),
                ('content', models.CharField(max_length=500)),
                ('ttl', models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(60)])),
                ('priority', models.PositiveSmallIntegerField(blank=True, help_text='MX/SRV only.', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='domains.domain')),
            ],
            options={
                'ordering': ['record_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegistrarProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('manual', 'Manual (no real registration - development/testing only)')], default='manual', max_length=20)),
                ('sandbox', models.BooleanField(default=True, help_text="Use the registrar's test/sandbox API where supported.")),
                ('credentials_encrypted', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_registrar_provider')],
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.registrarprovider'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_registration', 'pending_transfer_in', 'active', 'expired'))), fields=('name',), name='unique_live_domain_name'),
        ),
    ]
