# Generated by Django 5.2.17 on 2026-09-25 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_phase11_reminders'),
        ('clients', '0002_phase07_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Turn the programme off: links stop tracking, nobody can join and no new commissions are created.')),
                ('require_approval', models.BooleanField(default=True, help_text='Staff approve each new affiliate before their link works.')),
                ('cookie_days', models.PositiveSmallIntegerField(default=30, help_text='How long a visitor who followed a referral link is remembered for when they sign up.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('commission_kind', models.CharField(choices=[('percentage', 'Percentage of the sale'), ('fixed', 'Fixed amount per sale')], default='percentage', max_length=12)),
                ('commission_value', models.DecimalField(decimal_places=2, default=10, help_text='A percentage (e.g. 10) or an amount, by the type above.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('recurring_months', models.PositiveSmallIntegerField(default=0, help_text="Commission on every payment for this many months after the customer signs up. 0 = only on the customer's first paid invoice.", validators=[django.core.validators.MaxValueValidator(60)])),
                ('hold_days', models.PositiveSmallIntegerField(default=14, help_text='A commission stays Pending this long (a refund window) before it is approved automatically.', validators=[django.core.validators.MaxValueValidator(90)])),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=50, help_text='An affiliate must have at least this much approved to be paid.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('program_terms', models.TextField(blank=True, help_text='Shown to people joining the programme.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'affiliate settings',
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Used in the referral link.', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('commission_kind', models.CharField(blank=True, choices=[('percentage', 'Percentage of the sale'), ('fixed', 'Fixed amount per sale')], help_text="Blank = the programme's default rule.", max_length=12)),
                ('commission_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_details', models.TextField(blank=True, help_text='Where to send payouts (bank account, wallet number...). Visible to the affiliate and to staff who manage affiliates.', max_length=1000)),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Visitors who followed the link (a rough count).')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Shown to the affiliate.', max_length=500)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(help_text='e.g. Bank transfer, JazzCash.', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='The transaction ID.', max_length=200)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='affiliates.affiliate')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('link', 'Referral link'), ('staff', 'Added by staff')], default='link', max_length=8)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='affiliates.affiliate')),
                ('attributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='What the commission is worked out on: the invoice excluding tax, after discount.', max_digits=12)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage of the sale'), ('fixed', 'Fixed amount per sale')], max_length=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='The percentage or amount that applied.', max_digits=12)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='What it was when the invoice was paid.', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='What it is now (lower after a refund).', max_digits=12)),
                ('eligible_at', models.DateTimeField(help_text='When the hold ends and it can be approved automatically.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('needs_review', models.BooleanField(default=False, help_text='The invoice was refunded after this was paid out.')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.affiliate')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='billing.invoice')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.payout')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.referral')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='affiliate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_kind', ''), ('commission_value__isnull', True)), models.Q(models.Q(('commission_kind', ''), _negated=True), ('commission_value__isnull', False)), _connector='OR'), name='affiliate_rule_kind_and_value_together'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='commission_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('payout__isnull', False), _connector='OR'), name='paid_commission_has_a_payout'),
        ),
    ]
