# Generated by Django 5.2.17 on 2026-09-24 19:50

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0002_server_api_port_server_api_token_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text='Primary domain for this hosting account.', max_length=253)),
                ('username', models.CharField(help_text='cPanel account username.', max_length=16, validators=[django.core.validators.RegexValidator(re.compile('^[a-z][a-z0-9]{0,15}$'), 'Must start with a letter and contain only lowercase letters and numbers (max 16 characters).')])),
                ('status', models.CharField(choices=[('pending', 'Pending Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('suspend_reason', models.CharField(blank=True, max_length=500)),
                ('last_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('disk_used_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_limit_mb', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited/unknown.', null=True)),
                ('bandwidth_used_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('bandwidth_limit_mb', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited/unknown.', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosting_accounts', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosting_accounts', to='products.product')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_accounts', to='products.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'active', 'suspended'))), fields=('username',), name='unique_live_hosting_username')],
            },
        ),
    ]
