# Generated by Django 5.2.17 on 2026-09-25 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_cycle',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='custom_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Paid through this date.', null=True),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='term_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='term_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
