# Generated by Django 5.2.17 on 2026-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_phase08_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='suspended_for_nonpayment',
            field=models.BooleanField(default=False, help_text='Suspended automatically because the renewal was not paid; lifted when it is.'),
        ),
    ]
