# Generated by Django 5.2.17 on 2026-09-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_phase08_terms'),
        ('clients', '0002_phase07_billing'),
        ('domains', '0001_initial'),
        ('hosting', '0002_phase08_terms'),
        ('products', '0002_server_api_port_server_api_token_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('renewal', 'Renewal'), ('upgrade', 'Upgrade')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('applied', 'Applied'), ('failed', 'Paid - needs attention'), ('void', 'Void')], db_index=True, default='pending', max_length=10)),
                ('billing_cycle', models.CharField(blank=True, max_length=16)),
                ('custom_months', models.PositiveSmallIntegerField(default=0)),
                ('period_months', models.PositiveSmallIntegerField(help_text='Length of the term this change buys.')),
                ('paid_value', models.DecimalField(decimal_places=2, help_text="What this change adds to the term's valid paid value (ex tax).", max_digits=12)),
                ('expected_expires_at', models.DateTimeField(blank=True, help_text="The service's expiry when this was invoiced.", null=True)),
                ('calculation', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_changes', to='clients.client')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_changes', to='domains.domain')),
                ('from_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('hosting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_changes', to='hosting.hostingaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_changes', to='billing.invoice')),
                ('to_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('domain__isnull', True), ('hosting_account__isnull', False)), models.Q(('domain__isnull', False), ('hosting_account__isnull', True)), _connector='OR'), name='service_change_exactly_one_service'), models.UniqueConstraint(condition=models.Q(('hosting_account__isnull', False), ('status', 'pending')), fields=('hosting_account',), name='one_pending_change_per_hosting_account'), models.UniqueConstraint(condition=models.Q(('domain__isnull', False), ('status', 'pending')), fields=('domain',), name='one_pending_change_per_domain')],
            },
        ),
    ]
