"""
Print every URL route as a Markdown table: area, path, URL name, view and who may open it.

The inventory is read from Django's URL resolver, so it cannot drift from the code. "Access" is worked out from the
view's decorators or class (best effort; the authorization tests are the authority). Used for the roadmap's route
inventory (``docs/route-inventory.md``) and as the starting point for the link-integrity harness (Phase D2).

    python manage.py route_inventory > docs/route-inventory.md
"""
import inspect
import re

from django.core.management.base import BaseCommand
from django.urls import URLPattern, URLResolver, get_resolver

AREAS = (("api/", "API"), ("staff/", "Staff"), ("account/", "Customer"), ("admin/", "Django admin"))


def walk(patterns, prefix="", namespace=""):
    for pattern in patterns:
        if isinstance(pattern, URLResolver):
            nested = namespace + pattern.namespace + ":" if pattern.namespace else namespace
            yield from walk(pattern.url_patterns, prefix + str(pattern.pattern), nested)
        elif isinstance(pattern, URLPattern):
            yield prefix + str(pattern.pattern), (namespace + pattern.name) if pattern.name else "", pattern.callback


def area_of(path):
    return next((label for prefix, label in AREAS if path.startswith(prefix)), "Public")


def view_label(callback):
    cls = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
    target = cls or inspect.unwrap(callback)
    return f"{target.__module__.replace('apps.', '')}.{target.__name__}"


def permission_aliases(module_source):
    """``VIEW = portal_permission_required(perm("view_x"))`` style aliases -> the permissions they require."""
    found = {}
    for name, body in re.findall(r"^([A-Z_]+)\s*=\s*(portal_permission_required\([^\n]*\))", module_source, re.M):
        found[name] = re.findall(r'perm\("(\w+)"\)', body)
    return found


def access_of(callback):
    cls = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
    target = cls or inspect.unwrap(callback)
    if cls and cls.__name__ in ("RedirectView", "RetiredPath"):
        return "public (redirects)"
    try:
        source = inspect.getsource(target)
        module_source = inspect.getsource(inspect.getmodule(target))
    except (OSError, TypeError):
        return "?"
    notes = []
    if cls:
        perms = sorted(set(re.findall(r'perm\("(\w+)"\)', source)))
        for marker, note in (("PublicReadPermission", "public read"), ("AllowAny", "anonymous"),
                             ("IsAuthenticated", "signed in"), ("AuthenticatedReadPermission", "signed in (read)")):
            if marker in source:
                notes.append(note)
        if perms:
            notes.append("perm: " + ", ".join(perms))
        elif "HasPortalPermission" in source:
            notes.append("perm: (see class)")
        return "; ".join(notes) or "signed in"
    head = source.split("def ", 1)[0]
    perms = set(re.findall(r'portal_permission_required\([^)]*perm\("(\w+)"\)', head))
    aliases = permission_aliases(module_source)
    for token in re.findall(r"@([A-Z_]+)\b", head):
        perms.update(aliases.get(token, []))
    if "login_required" in head:
        notes.append("signed in")
    if "reviewer_required" in head:
        notes.append("perm: view_hosting or view_domains")
    if perms:
        notes.append("perm: " + ", ".join(sorted(perms)))
    if "_login_and_permission" in source:
        notes.append("perm: view_reports")
    if "require_POST" in head:
        notes.append("POST only")
    if not notes and "request.user" in source:
        notes.append("checked in view")
    return "; ".join(notes) or "public"


def collect():
    rows = []
    for path, name, callback in walk(get_resolver().url_patterns):
        if "(?P<format>" in path or (path.startswith("admin/") and path != "admin/"):
            continue
        clean = "/" + path.replace("^", "").replace("$", "")
        rows.append((area_of(path), clean, name or "(unnamed)", view_label(callback), access_of(callback)))
    return rows


class Command(BaseCommand):
    help = "Print every URL route (area, path, name, view, access) as a Markdown table."

    def handle(self, *args, **options):
        rows = collect()
        counts = {}
        for row in rows:
            counts[row[0]] = counts.get(row[0], 0) + 1
        out = self.stdout.write
        blank = "\n"
        out("# Route inventory")
        out(blank)
        out("Generated by `python manage.py route_inventory` from Django's URL resolver. "
            "Access is read from each view's decorators or class (best effort).")
        out(blank)
        out(f"**{len(rows)} routes:** " + ", ".join(f"{n} {a}" for a, n in sorted(counts.items())) + ".")
        for area in ("Public", "Customer", "Staff", "API", "Django admin"):
            section = [r for r in rows if r[0] == area]
            if not section:
                continue
            out(blank)
            out(f"## {area} ({len(section)})")
            out(blank)
            out("| Path | Name | View | Access |")
            out("|---|---|---|---|")
            for _, path, name, view, access in section:
                out(f"| `{path}` | `{name}` | {view} | {access} |")
