# Generated by Django 5.2.17 on 2026-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='No tax is charged on new orders and invoices. Staff only.'),
        ),
    ]
