# Generated by Django 5.2.17 on 2026-09-25 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_phase11_reminders'),
        ('clients', '0002_phase07_billing'),
        ('domains', '0001_initial'),
        ('hosting', '0003_phase12_nonpayment_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_after_days', models.PositiveSmallIntegerField(default=3, help_text='The service is Overdue until this many days after it expires, then in its Grace period (the customer gets a final notice).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('suspend_after_days', models.PositiveSmallIntegerField(default=7, help_text='Days after expiry when an unpaid hosting account is suspended.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('terminate_after_days', models.PositiveSmallIntegerField(default=30, help_text='Days after expiry when a hosting account suspended for non-payment is terminated.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)])),
                ('auto_suspend', models.BooleanField(default=True, help_text='Suspend unpaid accounts automatically.')),
                ('auto_terminate', models.BooleanField(default=False, help_text="Terminate accounts automatically. Termination deletes the customer's data, so it is off unless you turn it on; otherwise staff terminate by hand.")),
                ('unsuspend_on_payment', models.BooleanField(default=True, help_text='Lift an automatic suspension as soon as the renewal is paid.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'lifecycle settings',
            },
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_behalf', models.BooleanField(default=False, help_text='Started by staff, not by the customer.')),
                ('reason_code', models.CharField(choices=[('too_expensive', 'Too expensive'), ('not_needed', 'I no longer need it'), ('moving', 'Moving to another provider'), ('service', 'Unhappy with the service'), ('temporary', 'It was only temporary'), ('other', 'Other')], max_length=16)),
                ('reason_text', models.CharField(blank=True, max_length=1000)),
                ('timing', models.CharField(choices=[('immediate', 'Immediately'), ('end_of_term', 'At the end of the paid period')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10)),
                ('term_expires_at', models.DateTimeField(blank=True, help_text="The service's paid-through date when asked.", null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Shown to the customer.', max_length=1000)),
                ('effective_at', models.DateTimeField(blank=True, help_text='When the service ends (set on approval).', null=True)),
                ('auto_renew_before', models.BooleanField(blank=True, help_text="A domain's auto-renew setting before approval, restored if withdrawn.", null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_error', models.CharField(blank=True, max_length=500)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='Set while a worker is carrying it out.', null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='clients.client')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='domains.domain')),
                ('hosting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='hosting.hostingaccount')),
                ('refund_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.transaction')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.transaction')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('domain__isnull', True), ('hosting_account__isnull', False)), models.Q(('domain__isnull', False), ('hosting_account__isnull', True)), _connector='OR'), name='cancellation_exactly_one_service'), models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('hosting_account',), name='one_open_cancellation_per_hosting'), models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('domain',), name='one_open_cancellation_per_domain'), models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='cancellation_refund_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='LifecycleNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=20)),
                ('term_expires_at', models.DateTimeField()),
                ('hosting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_notices', to='hosting.hostingaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hosting_account', 'kind', 'term_expires_at'), name='one_lifecycle_notice_per_term')],
            },
        ),
    ]
