# Generated by Django 5.2.17 on 2026-09-25 18:00

import apps.branding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Blank = the SITE_NAME setting.', max_length=100)),
                ('primary_color', models.CharField(default='#2459d6', help_text='Buttons, links and the navigation bar. Must be dark enough for white text.', max_length=7, validators=[apps.branding.models.validate_hex])),
                ('accent_color', models.CharField(default='#1f7a4d', help_text='Highlights and positive actions.', max_length=7, validators=[apps.branding.models.validate_hex])),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('date_format', models.CharField(choices=[('%d %b %Y', '25 Sep 2026'), ('%Y-%m-%d', '2026-09-25'), ('%d/%m/%Y', '25/09/2026'), ('%m/%d/%Y', '09/25/2026')], default='%d %b %Y', max_length=12)),
                ('money_format', models.CharField(choices=[('code_before', 'USD 1,234.50'), ('code_after', '1,234.50 USD'), ('plain', '1,234.50')], default='code_before', max_length=12)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('logo_type', models.CharField(blank=True, editable=False, max_length=30)),
                ('favicon', models.BinaryField(blank=True, null=True)),
                ('favicon_type', models.CharField(blank=True, editable=False, max_length=30)),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Bumped on every change (cache busting).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'brand settings',
            },
        ),
    ]
