# Generated by Django 5.2.17 on 2026-09-25 20:57

import apps.branding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='accent_color',
            field=models.CharField(default='#1f7a4d', help_text='Highlights and call-to-action buttons; white or dark text is chosen to suit it.', max_length=7, validators=[apps.branding.models.validate_hex]),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='primary_color',
            field=models.CharField(default='#2459d6', help_text='Buttons, links and highlights. Must be dark enough for white text.', max_length=7, validators=[apps.branding.models.validate_hex]),
        ),
    ]
