# Generated by Django 5.2.17 on 2026-09-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_phase11'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='delivery',
            field=models.CharField(blank=True, choices=[('smtp', 'Mail server'), ('fallback', 'No provider set up')], max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='first_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, help_text="The Message-ID header, to find it in a mail server's log.", max_length=255),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('queued', 'Queued'), ('failed', 'Attempt failed'), ('sent', 'Handed to the mail server'), ('resent', 'Sent again by staff'), ('opened', 'Opened'), ('clicked', 'Link clicked')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.emailmessage')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='notifications.emailmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
